global using Xunit;
global using Microsoft.AspNetCore.Http;
global using Moq;
global using Hexagonal_Refactoring.Controllers;
global using Hexagonal_Refactoring.DTOs;
global using Hexagonal_Refactoring.Models;
global using Hexagonal_Refactoring.Repositories;
global using Hexagonal_Refactoring.Services;
global using Microsoft.AspNetCore.Mvc;
